INSERT INTO Post (user_id, img, description, created_on ) Values (1, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKQPfMa7bIEPRVzR6yp9e7g8gmlQFC1eL1-g&usqp=CAU', 'All penguin species share counter-shading camouflage. This means they have a lighter belly and a darker back, and helps them camouflage from predators above and below them. ', '2022-4-22');
INSERT INTO Post (user_id, img, description, created_on ) Values (2, 'https://th.bing.com/th/id/OIP.BHpZl8pR33AOgCT7JiREKwHaLG?w=115&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7', 'A good gauge of a male lion’s age is the darkness of his mane. The darker the mane, the older the lion.', '2022-4-23');
INSERT INTO Post (user_id, img, description, created_on ) Values (3, 'https://th.bing.com/th/id/OIP.v00YDzUx-Nmbqtz1WZ4yWAHaE8?w=237&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7', 'Flamingos stay together for the rest of their lives. Some couples have been together for 50 years or more.', '2022-4-23');
INSERT INTO Post (user_id, img, description, created_on ) Values (4, 'https://th.bing.com/th/id/OIP.mTXO4v9r0m53cramgoRvtQHaEy?w=274&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7', 'Ducks are some of the most common birds in North America. They can be found on ponds, lakes, and streams all over the continent. In this article, we’ll explore 23 fun facts about ducks that you may not have known before.', '2022-4-23');
INSERT INTO Post (user_id, img, description, created_on ) Values (5, 'https://jooinn.com/images/strange-animals-5.jpg', 'There are 130 different species of ducks in the world.', '2022-4-23');
INSERT INTO Post (user_id, img, description, created_on ) Values (6, 'https://th.bing.com/th/id/OIP.iXvEDuv2D7rz76A3DkcFlgHaEK?w=283&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7', 'Seventy percent of people sign their dog’s name on their holiday cards.', '2022-4-24');
INSERT INTO Post (user_id, img, description, created_on ) Values (7, 'https://th.bing.com/th/id/OIP.DIDXqNLhXQM11oDA22vddAHaFk?w=245&h=184&c=7&r=0&o=5&dpr=1.5&pid=1.7', 'City ducks have a different accent than country ducks – typically louder!', '2022-4-24');
INSERT INTO Post (user_id, img, description, created_on ) Values (8, 'https://th.bing.com/th/id/OIP.FU2Iu_YdvQ7z7j1kDxzcVQHaE8?w=277&h=185&c=7&r=0&o=5&dpr=1.5&pid=1.7', 'Pigs are omnivorous animals as they feed on both plants and animals.', '2022-4-25');
INSERT INTO Post (user_id, img, description, created_on ) Values (9, 'https://th.bing.com/th/id/OIP.R_nhfVhECX7WEUxNTOZlrgHaEo?w=315&h=197&c=7&r=0&o=5&dpr=1.5&pid=1.7', 'Tigers are the largest amongst other wild cats', '2022-4-25');
INSERT INTO Post (user_id, img, description, created_on ) Values (10, 'https://th.bing.com/th/id/OIP.pU35dWul79K5ePwnG6hwrAHaE8?w=274&h=183&c=7&r=0&o=5&dpr=1.5&pid=1.7', 'A baby rabbit is called a kit, a female is called a doe and a male is called a buck.', '2022-4-25');
INSERT INTO Post (user_id, img, description, created_on ) Values (11, 'https://th.bing.com/th/id/OIP.yxcekii72eK21_4n-_FZEQHaE8?w=298&h=199&c=7&r=0&o=5&dpr=1.5&pid=1.7', 'Parrots eat with their feet.', '2022-4-26');
INSERT INTO Post (user_id, img, description, created_on ) Values (12, 'https://th.bing.com/th/id/OIP.YLpxJRzRRCoF8U-qd4G57gHaFj?w=261&h=196&c=7&r=0&o=5&dpr=1.5&pid=1.7', 'Polar bears are found in the frozen wilds of the Arctic, in Canada, Alaska (US), Greenland, Russia and Norway.', '2022-4-26');
INSERT INTO Post (user_id, img, description, created_on ) Values (13, 'https://www.bing.com/th?id=OIP.sYiQulbHMQPehtadLIsyWgHaLH&w=204&h=306&c=8&rs=1&qlt=90&o=6&dpr=1.5&pid=3.1&rm=2', 'Bears are extraordinarily intelligent animals. They have far superior navigation skills to humans; excellent memories; large brain to body ratio; and use tools in various contexts from play to hunting.', '2022-4-26');
INSERT INTO Post (user_id, img, description, created_on ) Values (14, 'https://www.bing.com/th?id=OIP.b2DyhFvSkV18o1ZfFwBh_wHaFj&w=288&h=216&c=8&rs=1&qlt=90&o=6&dpr=1.5&pid=3.1&rm=2', 'The tiger is the national animal of both India and Bangladesh.', '2022-4-26');
INSERT INTO Post (user_id, img, description, created_on ) Values (15, 'https://th.bing.com/th/id/OIP.02b6Ka46Co6ccC5k1R7ucgHaE8?w=242&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7', 'Behavior. Gazelles are social animals that live in groups composed of as many as 700 members. Sometimes, females and males live in separate groups.', '2022-4-26');
INSERT INTO Post (user_id, img, description, created_on ) Values (16, 'https://th.bing.com/th/id/OIP.WehdCp8h0SL1HI7s3LVp3wHaEo?w=255&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7', 'Life span. Interesting facts of the zebra, that their average life span in the wild world is 25 years and up to 40 years in captivity.', '2022-4-26');
INSERT INTO Post (user_id, img, description, created_on  ) Values (17, 'https://th.bing.com/th/id/OIP.X5cEhI0OXTG-Zil1yfrrwwHaFj?w=230&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7', 'Squirrels are fantastic acrobats. In fact, it’s thought that they are able to jump around ten times their own body lengths when they need to.', '2022-4-26');
INSERT INTO Post (user_id, img, description, created_on ) Values (18, 'https://th.bing.com/th/id/R.6324f3ebe4f9b03aad59441fd7a7ce6a?rik=gDQtb7QnxhKVuQ&pid=ImgRaw&r=0', 'Bears care deeply about family members. They will risk their lives and even fight to the death in order to save a cub or sibling from danger.', '2022-4-26');

