# Anything that goes here is made globally for all profiles.
spring:
  application:
    name: User-CRUD

---
# Anything that goes here is made specifically for dev's profile.
spring:
  profiles: dev

---
# Anything that goes here is made specifically for clouds's profile.
# Cloud is the default profile that Google Cloud Foundry makes your application use if you do not override it.
spring:
  profiles: cloud


---
# Anything that goes here is made specifically for local's profile.
spring:
  profiles: cloud, default
server:
  port: 8080
ui:
  url:
post:
  url:
comment:
  url:
user:
  url:

---
# Anything that goes here is made specifically for local's profile.
spring:
  profiles: local
server:
  port: 8087
ui:
  url: http://localhost:4200
post:
  url: http://localhost:8085
comment:
  url: http://localhost:8086
user:
  url: http://localhost:8087



